# run flake8 styleguide tests
check_style:
  image: python:3.8
  stage: test
  before_script:
  - python3 -V
  - pip3 install -U -r requirements.txt
  script:
    - flake8 . --config=setup.cfg --output-file=outputs/flake8_report.log --tee
  artifacts:
    paths:
      - outputs/flake8_report.log
  allow_failure: true
  only:
    - master

publish_package:
  image: python:latest
  stage: deploy
  needs: ['check_style']
  when: manual
  script:
    - pip3 install twine
    - python3 setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.uni.lu/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
